### ISSUE TITLE
Magento 1.9 activation error

### ISSUE THREAD

**Issue by xStarman** [mercadopago/cart-magento#247]
When I active the module in app/etc/modules/MercadoPago_Core.xml, and try to configure some payment method at admin page (system_config/edit/section/payment) it shows the following error.

PS: It had worked before and stopped working, so I had to disable

Trace:
#0 /var/www/html/m/includes/src/MercadoPago_Lib_RestClient.php(92): MercadoPago_Lib_RestClient::exec('GET', '/item_categorie...', NULL, 'application/jso...', Array)
#1 /var/www/html/m/includes/src/MercadoPago_Core_Model_Source_CategoryId.php(24): MercadoPago_Lib_RestClient::get('/item_categorie...')
#2 /var/www/html/m/includes/src/Mage_Adminhtml_Block_System_Config_Form.php(463): MercadoPago_Core_Model_Source_CategoryId->toOptionArray(false)
#3 /var/www/html/m/includes/src/Mage_Adminhtml_Block_System_Config_Form.php(229): Mage_Adminhtml_Block_System_Config_Form->initFields(Object(Varien_Data_Form_Element_Fieldset), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element))
#4 /var/www/html/m/includes/src/Mage_Adminhtml_Block_System_Config_Form.php(164): Mage_Adminhtml_Block_System_Config_Form->_initGroup(Object(Varien_Data_Form), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element))
#5 /var/www/html/m/includes/src/Mage_Adminhtml_Block_System_Config_Edit.php(92): Mage_Adminhtml_Block_System_Config_Form->initForm()
#6 /var/www/html/m/app/code/core/Mage/Adminhtml/controllers/System/ConfigController.php(107): Mage_Adminhtml_Block_System_Config_Edit->initForm()
#7 /var/www/html/m/includes/src/__default.php(14339): Mage_Adminhtml_System_ConfigController->editAction()
#8 /var/www/html/m/includes/src/__default.php(18831): Mage_Core_Controller_Varien_Action->dispatch('edit')
#9 /var/www/html/m/includes/src/__default.php(18361): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#10 /var/www/html/m/includes/src/__default.php(21317): Mage_Core_Controller_Varien_Front->dispatch()
#11 /var/www/html/m/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#12 /var/www/html/m/index.php(83): Mage::run('', 'store')
#13 {main}

PHP 5.6
Amazon Linux EC2
Magento 1.9.3.7 Comunity #

**Comment by barbazul** [comment]
Looks like your server might had some issues connecting to MercadoPago.

It has happened to me in the past and it fixes itself after a while.

However this shows that the module requires more defensive programming

**Comment by PauloBoaventura** [comment]
PT/BR
Estou tendo o mesmo problema...
Ele estava funcionando perfeitamente...
Mas apos a atualizacao do magento para 1.9.3.8, ele esta dando este erro...
Tentei desistalar pelo Magento Conecct e instalar novamente...
Alguem pode ajudar???
===========================================
ENG
I'm having the same problem...
It was working perfectly ...
But after upgrading from magento to 1.9.3.8, he's giving this error ...
I tried to uninstall Magento Connect and install again ...
Can someone help ???

Desenvelopers: @go-loco
@jsotuyod
@sebagun
@thiagocaggiano
@tomidelucca


Agradeço desde já!
