### ISSUE TITLE
Erro MP magento compilado.

### ISSUE THREAD

**Issue by andretx** [mercadopago/cart-magento#270]
Olá depois da atualização do módulo estou encontrando alguns problemas.

Segue...
O problema persiste quando o magento está compilado.
O pior problema é o seguinte. 
**1 ->** A página de admin gera um erro na tela quando tento acessar as configurações do módulo em "Configurações -> Sistema -> Vendas - Formas de Pagamento"

Erro gerado:
`a:5:{i:0;s:51:"Problem with the SSL CA cert (path? access rights?)";i:1;s:2071:"#0 includes/src/MercadoPago_Lib_RestClient.php(92): MercadoPago_Lib_RestClient::exec('GET', '/item_categorie...', NULL, 'application/jso...', Array)
#1 intenso/includes/src/MercadoPago_Core_Model_Source_CategoryId.php(24): MercadoPago_Lib_RestClient::get('/item_categorie...')
#2 includes/src/Mage_Adminhtml_Block_System_Config_Form.php(463): MercadoPago_Core_Model_Source_CategoryId->toOptionArray(false)
#3 includes/src/Mage_Adminhtml_Block_System_Config_Form.php(229): Mage_Adminhtml_Block_System_Config_Form->initFields(Object(Varien_Data_Form_Element_Fieldset), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element))
#4 includes/src/Mage_Adminhtml_Block_System_Config_Form.php(164): Mage_Adminhtml_Block_System_Config_Form->_initGroup(Object(Varien_Data_Form), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element))
#5 includes/src/Mage_Adminhtml_Block_System_Config_Edit.php(92): Mage_Adminhtml_Block_System_Config_Form->initForm()
#6 app/code/core/Mage/Adminhtml/controllers/System/ConfigController.php(107): Mage_Adminhtml_Block_System_Config_Edit->initForm()
#7 includes/src/__default.php(14363): Mage_Adminhtml_System_ConfigController->editAction()
#8 includes/src/__default.php(18855): Mage_Core_Controller_Varien_Action->dispatch('edit')
#9 includes/src/__default.php(18385): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#10 includes/src/__default.php(21341): Mage_Core_Controller_Varien_Front->dispatch()
#11 app/Mage.php(684): Mage_Core_Model_App->run(Array)
#12 index.php(83): Mage::run('', 'store')
#13 {main}";s:3:"url";s:89:"/index.php/admin/system_config/edit/section/payment/key/642eb81a1745e9ab3a225d2d6891eb90/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"admin";}`

**2 ->** O segundo ero é que quando compilado o magento o mp não inclui os arquivos javascript's relacionados ao pagamento. Sendo assim as opções de pagamento não aparecem no checkout. Obs: acredito eu que este problema é culpa do primeiro erro citado acima.

Já pesquisei reinstalei o módulo, enfim fiz de tudo e nada. Alguém tem uma dica ou solução?

desde já agradeço... 
valeu.

**Comment by andretx** [comment]
Solução do problema: https://github.com/mercadopago/cart-magento/issues/220#issuecomment-337303721
